SET(CMAKE_C_COMPILER avr-gcc)
SET(CMAKE_CXX_COMPILER avr-g++)

SET(CSTANDARD "-std=gnu99")
SET(CWARN "-Wall")
SET(COPT "-O2")
SET(CMCU "-mmcu=atmega328p")
SET(CDEFS "-DF_CPU=20000000")
SET(CEXTRAS "")


SET(CFLAGS "${CMCU} ${CDEFS} ${COPT} ${CWARN} ${CSTANDARD} ${CEXTRAS}")
SET(CXXFLAGS "${CMCU} ${CDEFS} ${COPT} ${CWARN} ${CEXTRAS}")
SET(CMAKE_SHARED_LIBRARY_LINK_CXX_FLAGS "")

SET(CMAKE_C_FLAGS  ${CFLAGS})
SET(CMAKE_CXX_FLAGS ${CXXFLAGS})