# -*- coding:utf-8 -*-

import serial
import time
import __builtin__
import log
import instance

log = log.Log(__name__)

class Danse :
    def __init__(self) :
        if hasattr(__builtin__.instance, 'actionInstance') :
            self.actionneur =  __builtin__.instance.actionInstance
            a = self.actionneur
        else :
            log.logger.error("Impossible d'importer les actionneurs")
    
    def danse(self) :
        
        time.sleep(1)
        self.actionneur.danse_mvt1()
    
    def danse_epicSax(self):
        a.deplacer(110)
        time.sleep(1)
        
        a.deplacer(70, ["hg", "bg"])
        a.deplacer(140, ["hd", "bd"])
        time.sleep(0.5)
        a.deplacer(70, ["hd", "bd"])
        a.deplacer(140, ["hg", "bg"])
        time.sleep(0.5)
        a.deplacer(70, ["hg", "bg"])
        a.deplacer(140, ["hd", "bd"])
        time.sleep(0.5)
        a.deplacer(70, ["hd", "bd"])
        a.deplacer(140, ["hg", "bg"])
        time.sleep(0.5)
        
        time.sleep(0.5)
        a.deplacer(70, "bg")
        a.deplacer(140, "bd")
        time.sleep(0.5)
        a.deplacer(70, ["bd", "hg"])
        a.deplacer(140,["bg", "hd"])
        time.sleep(0.5)
        a.deplacer(70, ["bg", "hd"])
        a.deplacer(140,["bd", "hg"])
        time.sleep(0.5)
        a.deplacer(70, ["bd", "hg"])
        a.deplacer(140,["bg", "hd"])
        time.sleep(0.5)
        
        time.sleep(0.5)
        a.deplacer(140, ["bg", "hg"])
        a.deplacer(40,  ["bd", "hd"])
        time.sleep(0.5)
        a.deplacer(110, ["bg", "hg"])
        a.deplacer(70,  ["bd", "hd"])
        time.sleep(0.5)
        a.deplacer(90, ["bg", "hg"])
        a.deplacer(90,  ["bd", "hd"])
        time.sleep(0.5)
        a.deplacer(70, ["bg", "hg"])
        a.deplacer(110, ["bd", "hd"])
        time.sleep(0.5)
        a.deplacer(40, ["bg", "hg"])
        a.deplacer(140, ["bd", "hd"])
        time.sleep(0.5)
        
        
        
        
    def danse_mvt1(self) :
        self.actionneur.deplacer(90)
        time.sleep(1)
        self.actionneur.deplacer(160)
        time.sleep(1)
        self.actionneur.deplacer(0)
        time.sleep(1)
        self.actionneur.deplacer(45)
        time.sleep(1)
        self.actionneur.deplacer(120)
        time.sleep(1)
        self.actionneur.deplacer(45, "bg")
        time.sleep(0.3)
        self.actionneur.deplacer(45, "bd")
        time.sleep(0.3)
        self.actionneur.deplacer(45, "hg")
        self.actionneur.deplacer(45, "hd")
        time.sleep(0.3)
        self.actionneur.deplacer(100)
        time.sleep(0.2)
        self.actionneur.deplacer(120)
        time.sleep(0.3)
        self.actionneur.deplacer(140, "bg")
        self.actionneur.deplacer(140, "bd")

        self.actionneur.deplacer(160, "hg")
        self.actionneur.deplacer(160, "hd")
        time.sleep(0.5)
        self.actionneur.deplacer(45, "hd")
        self.actionneur.deplacer(45, "hg")
        self.actionneur.changerVitesse(100)
        self.actionneur.deplacer(20, "bd")
        self.actionneur.deplacer(20, "bg")
        self.actionneur.changerVitesse(500)
        time.sleep(0.5)
        self.actionneur.deplacer(160, "hg")
        self.actionneur.deplacer(160, "hd")
        time.sleep(0.5)
        self.actionneur.deplacer(45, "hd")
        self.actionneur.deplacer(45, "hg")
        time.sleep(0.5)
        self.actionneur.deplacer(160, "hg")
        self.actionneur.deplacer(160, "hd")
        time.sleep(0.5)
        self.actionneur.deplacer(45, "hd")
        self.actionneur.deplacer(45, "hg")
        time.sleep(0.5)

    def danse_mvt2(self) :
        self.actionneur.deplacer(40, "bg")
        self.actionneur.deplacer(40, "hg")
        self.actionneur.deplacer(160, "hd")
        self.actionneur.deplacer(160, "bd")
        time.sleep(0.5)
        self.actionneur.changerVitesse(150)
        self.actionneur.deplacer(40, "bd")
        self.actionneur.deplacer(40, "hd")
        self.actionneur.deplacer(160, "hg")
        self.actionneur.deplacer(160, "bg")
        time.sleep(1.5)
        self.actionneur.changerVitesse(500)
        self.actionneur.deplacer(40, "bg")
        self.actionneur.deplacer(40, "hg")
        self.actionneur.deplacer(160, "hd")
        self.actionneur.deplacer(160, "bd")
        time.sleep(0.5)
        self.actionneur.changerVitesse(150)
        self.actionneur.deplacer(40, "bd")
        self.actionneur.deplacer(40, "hd")
        self.actionneur.deplacer(160, "hg")
        self.actionneur.deplacer(160, "bg")
        time.sleep(1.5)
        self.actionneur.changerVitesse(400)
        self.actionneur.deplacer(40, "bg")
        self.actionneur.deplacer(160, "bd")
        time.sleep(1)
        self.actionneur.deplacer(160, "hd")
        self.actionneur.deplacer(40, "hg")
        self.actionneur.deplacer(160, "bg")
        self.actionneur.deplacer(40, "bd")
        time.sleep(0.7)
        self.actionneur.deplacer(90)
        time.sleep(1)
        self.actionneur.changerVitesse(500)
    
    
        
        self.actionneur.deplacer(80, "bg")
        self.actionneur.deplacer(80, "bd")
        self.actionneur.deplacer(100, "hg")
        self.actionneur.deplacer(100, "hd")
        time.sleep(0.5)
        self.actionneur.deplacer(70, "hg")
        self.actionneur.deplacer(70, "hd")
        self.actionneur.deplacer(110, "bg")
        self.actionneur.deplacer(110, "bd")
        time.sleep(0.5)
        self.actionneur.deplacer(60, "bg")
        self.actionneur.deplacer(60, "bd")
        self.actionneur.deplacer(120, "hg")
        self.actionneur.deplacer(120, "hd")
        time.sleep(1)
        self.actionneur.deplacer(70, "hg")
        self.actionneur.deplacer(70, "hd")
        self.actionneur.deplacer(110, "bg")
        self.actionneur.deplacer(110, "bd")
        time.sleep(0.5)
        self.actionneur.deplacer(80, "bg")
        self.actionneur.deplacer(80, "bd")
        self.actionneur.deplacer(100, "hg")
        self.actionneur.deplacer(100, "hd")
        time.sleep(0.5)
        self.actionneur.deplacer(90)
        time.sleep(1)
        
        #####################################
        
        self.actionneur.deplacer(80, "hg")
        time.sleep(0.3)
        self.actionneur.deplacer(100, "hg")
        time.sleep(0.3)
        self.actionneur.deplacer(80, "hg")
        time.sleep(0.3)
        self.actionneur.deplacer(100, "hg")
        time.sleep(0.3)
        
        self.actionneur.deplacer(80, "hg")
        self.actionneur.deplacer(80, "hd")
        time.sleep(0.25)
        self.actionneur.deplacer(100, "hg")
        self.actionneur.deplacer(100, "hd")
        time.sleep(0.25)
        self.actionneur.deplacer(80, "hg")
        self.actionneur.deplacer(80, "hd")
        time.sleep(0.25)
        self.actionneur.deplacer(100, "hg")
        self.actionneur.deplacer(100, "hd")
        time.sleep(0.25)
        
        self.actionneur.deplacer(80, "hg")
        self.actionneur.deplacer(80, "hd")
        self.actionneur.deplacer(80, "bd")
        time.sleep(0.2)
        self.actionneur.deplacer(100, "hg")
        self.actionneur.deplacer(100, "hd")
        self.actionneur.deplacer(100, "bd")
        time.sleep(0.2)
        self.actionneur.deplacer(80, "hg")
        self.actionneur.deplacer(80, "hd")
        self.actionneur.deplacer(80, "bd")
        time.sleep(0.2)
        self.actionneur.deplacer(100, "hg")
        self.actionneur.deplacer(100, "hd")
        self.actionneur.deplacer(100, "bd")
        time.sleep(0.2)
        
        self.actionneur.deplacer(80, "hg")
        self.actionneur.deplacer(80, "hd")
        self.actionneur.deplacer(80, "bd")
        self.actionneur.deplacer(80, "bg")
        time.sleep(0.15)
        self.actionneur.deplacer(100, "hg")
        self.actionneur.deplacer(100, "hd")
        self.actionneur.deplacer(100, "bd")
        self.actionneur.deplacer(100, "bg")
        time.sleep(0.15)
        
        self.actionneur.deplacer(80, "hg")
        self.actionneur.deplacer(80, "hd")
        self.actionneur.deplacer(80, "bd")
        self.actionneur.deplacer(80, "bg")
        time.sleep(0.08)
        self.actionneur.deplacer(100, "hg")
        self.actionneur.deplacer(100, "hd")
        self.actionneur.deplacer(100, "bd")
        self.actionneur.deplacer(100, "bg")
        time.sleep(0.08)
        self.actionneur.deplacer(80, "hg")
        self.actionneur.deplacer(80, "hd")
        self.actionneur.deplacer(80, "bd")
        self.actionneur.deplacer(80, "bg")
        time.sleep(0.08)
        self.actionneur.deplacer(100, "hg")
        self.actionneur.deplacer(100, "hd")
        self.actionneur.deplacer(100, "bd")
        self.actionneur.deplacer(100, "bg")
        time.sleep(0.08)
        self.actionneur.deplacer(80, "hg")
        self.actionneur.deplacer(80, "hd")
        self.actionneur.deplacer(80, "bd")
        self.actionneur.deplacer(80, "bg")
        time.sleep(0.08)
        self.actionneur.deplacer(100, "hg")
        self.actionneur.deplacer(100, "hd")
        self.actionneur.deplacer(100, "bd")
        self.actionneur.deplacer(100, "bg")
        time.sleep(0.08)
        self.actionneur.deplacer(80, "hg")
        self.actionneur.deplacer(80, "hd")
        self.actionneur.deplacer(80, "bd")
        self.actionneur.deplacer(80, "bg")
        time.sleep(0.08)
        self.actionneur.deplacer(100, "hg")
        self.actionneur.deplacer(100, "hd")
        self.actionneur.deplacer(100, "bd")
        self.actionneur.deplacer(100, "bg")
        time.sleep(0.08)
        
        self.actionneur.deplacer(160)

        
        

